### ISSUE TITLE
Problem with a missing scene.pck

### ISSUE THREAD

**Issue by Tfausx** [marcussacana/SiglusSceneManager#7]
Hello marcus, i hope you're having a great day! I was wondering if you can help me with a problem i have with certain game... The game in question it's for elise ～エリーゼのために～, this game got a new port in siglus engine recently. Well, i buy it the game yesterday to make a translation for it and... the game doesn't have Scene.pck in the archives; it's inside of the SiglusEngine.exe on the folder StartData\GameData\data. Well, i manage to open the .exe and extract the archive, but after made a modification, the game still reading the Scene.pck from the inside of the exe and not the modified one i put on the game folder. My question it's if there's a way to make the .exe read the Scene.pck of the folder and not from the exe?

I also have send you a mail with the link to download the game! Thanks in advance!

**Comment by marcussacana** [comment]
I will take a look, I don't think will be hard to do something if they don't modded the SiglusEngine VM

**Comment by marcussacana** [comment]
The game is protected with PlayDRM, I can't start the game by myself.
The PlayDRM encrypt the game file and only with the key we are able to decrypt it, I can't just 'crack it' without an key.
You can do 2 things, Crack/Remove the PlayDRM then share to me the cracked version or share your license to me try here. (What I really don't recommend since they verify our hwid and can ban your license)

Another possibility, but I'm not sure, you can just share with me the Scene.pck that you get and say me what is the decryption key that you found to the scene.pck, I will take a look in what can I do after that.

Also, if you are able to extract any other file from the .exe as well, like the dat folder that siglus games usually have, send it too, that will be necessary.

**Comment by Tfausx** [comment]
Sent it all!

**Comment by marcussacana** [comment]
Take a look in your email

**Comment by Tfausx** [comment]
Thank you very much again marcus! All works perfect now! Thank again for your time and kindness!


Have a nice day!
